version: "3"
services:
  selenium-rahul:
    image: topdandy/selenium-docker-test-v1
    entrypoint:
      java -cp "libs/*"  org.testng.TestNG  test-suites/testng.xml
    volumes:
      - ./output/result:/home/selenium-docker/test-output


